buildscript {
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:9.2.1'
        classpath 'com.google.gms:google-services:4.4.4'
        classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:2.4.0'
        classpath 'com.google.devtools.ksp:symbol-processing-gradle-plugin:2.3.9'
        classpath 'androidx.navigation:navigation-safe-args-gradle-plugin:2.9.8'
        classpath 'com.google.firebase:firebase-crashlytics-gradle:3.0.7'
        classpath 'com.google.firebase:perf-plugin:2.0.2'
        classpath 'com.google.dagger:hilt-android-gradle-plugin:2.59.2'
        classpath 'com.google.android.libraries.mapsplatform.secrets-gradle-plugin:secrets-gradle-plugin:2.0.1'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
        maven {
            name = 'GitHub'
            url = "https://maven.pkg.github.com/SoyMomo/soymomo_login_android"
            credentials {
                username = "$SoyMomoProjectPackagePermissionUser"
                password = "$SoyMomoProjectPackagePermissionToken"
            }
        }

    }
}

tasks.register('clean', Delete) {
    delete rootProject.buildDir
}
