package com.sosmartlabs.momotabletpadres.appinfo.model

/**
 * Class for handling app information
 */
data class AppInfo(
    val objectId: String?,
    var lang: String?,
    var country: String?,
    var screenshots: List<String>,
    var title: String?,
    var description: String?,
    var descriptionHTML: String?,
    var summary: String?,
    var installs: String?,
    var scoreText: String?,
    var currency: String?,
    var free: Boolean?,
    var size: String?,
    var offersIAP: Boolean?,
    var androidVersion: String?,
    var androidVersionText: String?,
    var IAPRange: String?,
    var developerId: String?,
    var developerEmail: String?,
    var developerWebsite: String?,
    var developer: String?,
    var privacyPolicy: String?,
    var developerInternalID: String?,
    var genre: String?,
    var developerAddress: String?,
    var familyGenre: String?,
    var familyGenreId: String?,
    var icon: String?,
    var headerImage: String?,
    var videoImage: String?,
    var contentRating: String?,
    var contentRatingDescription: String?,
    var video: String?,
    var released: String?,
    var version: String?,
    var adSupported: Boolean?,
    var editorsChoice: Boolean?,
    var appId: String?,
    var url : String?,
    var recentChanges: String?,
    var packageName: String?,
    val dugDescriptionHTML: String?,
    val saferAppAlternative: List<AppInfo>,
    val dugAnalysis: String?
    )
