package com.sosmartlabs.momotabletpadres.utils.model

import com.sosmartlabs.momotabletpadres.utils.firebase.CrashlyticsLog
import com.sosmartlabs.momotabletpadres.utils.model.FORMAT.*
import timber.log.Timber
import kotlin.random.Random

/**
 * Formats of Rut
 *
 * - [FULL]: 12.345.678-9
 * - [ONLY_DASH]: 12345678-9
 * - [ESCAPED]: 123456789
 */
enum class FORMAT {
    FULL,
    ONLY_DASH,
    ONLY_DASH_UPPERCASE,
    ESCAPED }

/**
 * RUT
 * Chilean personal ID
 *
 * @param number Numeric part of Rut (from 123-k, numeric part is "123")
 * @param dv Verifier code of Rut
 */
class Rut(number: String, dv: String) : Comparable<Rut> {

    /**
     * @property number Numeric part of Rut (from 123-k, numeric part is "123")
     */
    val number: Int

    /**
     * @property dv Verifier code of Rut
     */
    val dv: String

    /**
     * RUT Initializer
     * - Verifies the numeric part
     * - Verifies the check digit
     */
    init {
        require(number.matches(numberRgx.toRegex())){ "Invalid format" }
        require(dv.matches(dvRgx.toRegex())) { "Invalid check digit" }
        this.number = number.replace(".", "").toInt()
        this.dv = dv.lowercase()
    }

    /**
     * Methods
     */
    companion object Util {

        private const val numberRgx = """^([1-9]\d?(\.?\d{3}){0,2}|[1-9]\d{0,2}(\.?\d{3})?)$"""
        private const val dvRgx = """^([0-9]|k|K)$"""
        private const val ZERO = "0"
        private const val K = "k"
        private const val ELEVEN = 11
        private const val TEN = 10
        /**
         * Numerical series to calculate the check digit
         */
        private val SERIES = intArrayOf(2, 3, 4, 5, 6, 7)
        /**
         * Minimum - maximum range to be returned by a random RUT
         */
        private const val MIN_RANGE = 4_000_000
        private const val MAX_RANGE = 80_000_000

        /**
         * Transforms a RUT, given the numeric part and its check digit
         *
         * Examples of formats:
         *
         * - 12345678-k
         * - 12345678k
         * - 12.345.678-k
         * - 12.345.678k
         * - 12.345.678K
         *
         * @param rut Rut with its numerical part and check digit
         *
         * @return Instance of RUT
         */
        fun parse(rut: String): Rut? {
            try {
                if (rut.isEmpty() || rut == ZERO) return Rut("", "")

                val dv = rut.last().toString()
                val sub = rut.dropLast(1)
                val number = if (sub.last() == '-') sub.dropLast(1) else sub

                return Rut(number, dv)
            } catch (e: Exception) {
                Timber.e(e)
                CrashlyticsLog.recordNonFatalError(e, "Invalid format or digit of $rut")
                return null
            }
        }

        /**
         * Transforms a numeric part to a RUT
         *
         * @param number Numeric part of the RUT (e.g. if it is 123-k, it would be 123)
         *
         * @return RUT
         */
        fun parse(number: Int) : Rut = Rut(number.toString(), calcDv(number))

        /**
         * Calculates the verification digit
         *
         * @param number Numeric part of the rd number
         *
         * @return Verifying digit
         */
        fun calcDv(number: Int) : String {
            var copy = number
            var sum = 0
            var index = 0
            while (copy > 0) {
                sum += SERIES[index] * (copy % TEN)
                copy /= TEN
                index = if (index < SERIES.size - 1) index + 1 else 0
            }
            return dvFromResult(ELEVEN - (sum % ELEVEN))
        }

        /**
         * Maps the result of the calculation to the check digit
         *
         * @param result Result of check digit calculation
         *
         * @return Verifying digit
         */
        private fun dvFromResult(result: Int) : String = when(result) {
            ELEVEN -> ZERO
            TEN -> K
            else -> result.toString()
        }

        /**
         * Generates a RUT randomly
         *
         * @param min Minimum value that the numeric part of the RUT could have
         * @param max Maximum value that the numeric part of the RUT could have.
         * @param seed Indicates whether the RUT will be generated by a given seed. null if not to be applied.
         *
         * @return RUT random
         */
        private fun random(min: Int = MIN_RANGE, max: Int = MAX_RANGE, seed: Int? = null): Rut = parse(
            (if (seed == null) Random else Random(seed)).nextInt(min, max)
        )

        /**
         * Generates a list of RUT's of size [n] randomly
         *
         * @param n Size of the list
         * @param min Minimum value that the numeric part of the RUT could have
         * @param max Maximum value that the numerical part of the RUT could have
         * @param seed Indicates if the RUT will be generated by a given seed. null if not to be applied.
         *
         * @return List of size [n] containing RUT's in random form.
         */
        fun randoms(n: Int = 1, min: Int = MIN_RANGE, max: Int = MAX_RANGE, seed: Int? = null): List<Rut> {
            return List(n) { random(min, max, seed) }
        }

        /**
         * Generates a unique list of RUT's of size [n] randomly
         *
         * @param n Size of the list
         * @param min Minimum value that the numeric part of the RUT could have
         * @param max Maximum value that the numeric part of the RUT could have
         * @param seed Indicates if the RUT will be generated by a given seed. null if not to be applied.
         *
         * @return Unique list of size [n] containing RUT's in random form.
         */
        fun uniques(n: Int = 1, min: Int = MIN_RANGE, max: Int = MAX_RANGE, seed: Int? = null): List<Rut> {
            val set = mutableSetOf<Rut>()
            while(set.size < n) { set.add(random(min, max, seed)) }
            return set.toList()
        }

    }

    /**
     * Validates a RUT
     *
     * @return True if the RUT is valid
     */
    fun isValid() : Boolean = calcDv(number) == dv

    /**
     * Format the RUT
     *
     * - [FORMAT.FULL] -> RUT with dots and hyphen (12.345.678-k)
     * - [FORMAT.ONLY_DASH] -> RUT without dots and with hyphen (12345678-k)
     * - [FORMAT.ESCAPED] -> RUT without dots and dash (12345678k)
     *
     * @param format RUT format
     * @return RUT formatted
     */
    fun format(format: FORMAT = FORMAT.FULL) : String = when(format) {
        FULL -> "%,d-$dv".format(number).replace(",", ".")
        ONLY_DASH -> "$number-$dv"
        ONLY_DASH_UPPERCASE -> "$number-${dv.uppercase()}"
        ESCAPED -> "$number$dv"
    }

    /**
     * Compare this instance of RUT with another one.
     *
     * @param other The other instance of RUT
     *
     * @return Comparison value
     */
    override fun compareTo(other: Rut): Int = number.compareTo(other.number)

    /**
     * Structural equality
     *
     * @param other Other Instance (or null)
     */
    override fun equals(other: Any?): Boolean = if (other is Rut) other.number == number && other.dv == dv else false

    /**
     * @return Character string representation
     */
    override fun toString(): String = "Rut($number, $dv)"

    /**
     * First component of the destruction
     *
     * @return First component of the destruct (number, _)
     */
    operator fun component1() : Int = number

    /**
     * Second component of the destruction
     *
     * @return Second component of destruct (_, dv)
     */
    operator fun component2() : String = dv

    /**
     * Hash Code
     *
     * @return Hash value
     */
    override fun hashCode(): Int {
        var result = number
        result = 31 * result + dv.hashCode()
        return result
    }

}